import type { Metadata } from "next";
import { Inter, Cinzel_Decorative } from "next/font/google";
import Layout from "./layout/layout";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const cinzelDecorative = Cinzel_Decorative({
  variable: "--font-cinzel-decorative",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Meisterhaus Bed & Breakfast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${cinzelDecorative.variable} antialiased`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
